spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    # url: "jdbc:mysql://mysql-aws.c4v3j9tgecmv.us-east-1.rds.amazonaws.com:3306/itemsharingdatabase"
    # username: "root"
    # password: "{cipher}de8a2140acf533afcd9e1ee6f9156226581120ed6b49187e376694db634b7bad"
    # password: "Rochester24"
    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
    username: "hbstudent"
    password: "hbstudent"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
    
server:
  port: 8081

eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://54.235.233.109:8761/eureka/
      defaultZone: http://localhost:8761/eureka


security:
 basic:
   enabled: false

# security:
#  oauth2:
#   resource:
#     userInfoUri: http://54.235.233.109:8901/user
    
# signing:
#   key: 345345fsdgsf5345
  
# logging:
#   level:
#     com.netflix: WARN
#     org.springframework.web: WARN
#     com.itemsharing: DEBUG